### PR TITLE
Load before Essentials

### PR DESCRIPTION
**Pull request by Legoman99573**
This should resolve an issue with Essentials command still overriding this plugins /ban command

### CODE REVIEW

**Comment by garagepoort** [comment]
@Legoman99573 
Hi Legoman,
Thanks for the contribution. I do wonder, does the essentials plugin not have an option to disable the ban feature on their plugin. Because if so I would prefer people disabled the commands themselves. Because we can't really take into account all different plugins out there. Also another plugin might decide the load before us to overwrite the commands from Staff++.
I would just leave this up to configuration.

**Comment by Legoman99573** [comment]
> @Legoman99573
> Hi Legoman,
> Thanks for the contribution. I do wonder, does the essentials plugin not have an option to disable the ban feature on their plugin. Because if so I would prefer people disabled the commands themselves. Because we can't really take into account all different plugins out there. Also another plugin might decide the load before us to overwrite the commands from Staff++.
> I would just leave this up to configuration.

They do not have that option in essentialsx, but the thing with how spigot works is it will load which plugin is loaded first, which this case, essentials is loaded before this plugin, so spigot will default to essentials ban command instead of staff++'s ban command.

**Comment by garagepoort** [comment]
> > @Legoman99573
> > Hi Legoman,
> > Thanks for the contribution. I do wonder, does the essentials plugin not have an option to disable the ban feature on their plugin. Because if so I would prefer people disabled the commands themselves. Because we can't really take into account all different plugins out there. Also another plugin might decide the load before us to overwrite the commands from Staff++.
> > I would just leave this up to configuration.
> 
> They do not have that option in essentialsx, but the thing with how spigot works is it will load which plugin is loaded first, which this case, essentials is loaded before this plugin, so spigot will default to essentials ban command instead of staff++'s ban command.

Yes I understand the problem, it’s  unfortunate  essentialx does not have the option to configure this.
Now we have to configure this and if in the future another plugins decides to implement ban commands we again have to change our loadBefore. So that's why I would rather not hardcode it in our plugin as we can never have total control over it.
We can just keep fixing issues one by one.

I found this on the essentialsX wiki: https://github.com/EssentialsX/Essentials/wiki/Common-Issues#essentialsx-overrides-a-command-from-spigot-or-another-plugin

It suggest overwriting the alias to point it to a specific command. This way you only have to configure the alias one time and no other plugin can ever overwrite it. I think this would be a better approach?

**Comment by Legoman99573** [comment]
the change is ok for me, but i think its going to be a problem for others who use this plugin with essentialsx installed.

**Comment by garagepoort** [comment]
> the change is ok for me, but i think its going to be a problem for others who use this plugin with essentialsx installed.

Thanks, I will update the banning wiki page to explain this problem and the suggested solution.

**Pull request closed without merging**
